language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28

addons:
  sonarcloud:
    organization: "isnrv"

script:
  - sonar-scanner